services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cartdb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
  api:
    build: ./test
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
    environment:
      DATASOURCE_URL: 'jdbc:postgresql://db:5432/cartdb'
      DATASOURCE_USER: postgres
      DATASOURCE_PASSWORD: postgres
      FRONTEND_URL: localhost
  front-end:
      build: ./test-page-react
      container_name: test-page-react
      ports:
        - "80:80"
      environment:
        NEXT_PUBLIC_API_URL: http://localhost:8080
  certbot:
    image: certbot/certbot:latest
    volumes:
        - ./certbot/www/:/var/www/certbot/:rw
        - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
          - front-end
    command:
        - certonly --webroot --webroot-path=/var/www/certbot --email sanjewad@gmail.com --agree-tos --no-eff-email --staging -d ceylonspicehub.com.au  -d www.ceylonspicehub.com.au
volumes:
  certbot-etc:
  certbot-var:
  web-root:
      driver: local
      driver_opts:
        type: none
        ##device: /home/sammy/node_project/views/
        o: bind